title: stratigraphy.org
email: nick@kurrawong.ai
description: 
  The International Commission on Stratigraphy's website.
baseurl: "/"
url: "https://stratigraphy.org"
github_username:  nicholascar

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
