title: stratigraphy.org
email: nicholas.car@surroundaustralia.com
description: 
  The International Commission on Stratigraphy's website.
baseurl: "/"
url: "https://stratigraphy.org"
github_username:  nicholascar

# Build settings
theme: minima
plugins:
  - jekyll-feed
